# Spring properties
spring:
  application:
    name: jingzingBlog  # Service registers under this name
  profiles:
    active: dev
  thymeleaf:
    cache: false
  jade4j:
    caching: false
  # Redis数据库索引（默认为0）
  redis:
    database: 0
   # Redis服务器地址
    host: 192.168.5.111
   # Redis服务器连接端口
    port: 6379
   # Redis服务器连接密码（默认为空）
    password: soonfor@db1379
   # 连接超时时间（毫秒）
    timeout: 0
   # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 10
   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
   # 连接池中的最大空闲连接
      max-idle: 20

# HTTP Server
server:
  port: 7777   # 动态分配端口

druid:
  name: blog-db1
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
# 初始化大小，最小，最大
  initialSize: 10
  minIdle: 10
  maxActive: 200
# 配置获取连接等待超时的时间
  maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,log4j,config
# 合并多个DruidDataSource的监控数据
#   useGlobalDataSourceStat: true
  url: jdbc:mysql://192.168.5.111:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: soonfor
  #java -cp druid-1.0.16.jar com.alibaba.druid.filter.config.ConfigTools 你的密码(admin123) admin soonfor
  password: sfadmin1379!
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl.auto: update
  show_sql: false

#logging:
#  config:
#    classpath: logback-spring.xml
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

management:
  security:
    enabled: false

